baseurl = "https://franciscoyira.com/"
languageCode = "en-us"
theme = "hugo-theme-hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Enable to show reading time in minutes for posts
  showReadingTime = true
  rssFullText = false
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]
  [languages.en]
    title = "francisco yirá's blog"
    subtitle = "data science, tech, and +"
    keywords = ""
    copyright = ""
    menuMore = "More"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2th January 2006"
    dateFormatList = "2th January 2006"

    [languages.en.params.logo]
      logoText = "francisco yirá's blog"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "archive"
        name = "️🗃️ Archive"
        url = "/archive"
      [[languages.en.menu.main]]
        identifier = "subscribe"
        name = "🔔 Subscribe"
        url = "/subscribe"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "mastodon"
        name = "🌀 Threads"
        url = "https://www.threads.net/@francisco_yira"
      [[languages.en.menu.main]]
        identifier = "linkedin"
        name = "💼 LinkedIn"
        url = "https://www.linkedin.com/in/franciscoyira/"
      [[languages.en.menu.main]]
        identifier = "github"
        name = "🐙 GitHub"
        url = "https://github.com/franciscoyira"
      #[[languages.en.menu.main]]
      #  identifier = "about"
      #  name = "About"
      #  url = "/about"
      #[[languages.en.menu.main]]
      #  identifier = "change_lang"
      #  name = "Español"
      #  url = "/es"
      [[languages.en.menu.main]]
        identifier = "cv"
        name = "About Me+Portfolio"
        url = "https://cv.franciscoyira.com/"
        weight = 2

        
  [languages.es]
      title = "blog de francisco yirá"
      subtitle = "ciencia de datos, tecnología y +"
      keywords = ""
      copyright = ""
      menuMore = "Más"
      writtenBy = "Escrito por"
      readMore = "Leer más"
      readOtherPosts = "Leer otros posts"
      newerPosts = "Posts más recientes"
      olderPosts = "Posts más antiguos"
      minuteReadingTime = "min de lectura"
      dateFormatSingle = "2006-01-02"
      dateFormatList = "2006-01-02"
  
      [languages.es.params.logo]
        logoText = "blog de francisco yirá"
        logoHomeLink = "/es/"
      # or
      #
      # path = "/img/your-example-logo.svg"
      # alt = "Your example logo alt text"
  
      [languages.es.menu]
        [[languages.es.menu.main]]
          identifier = "archive"
          name = "Archivo"
          url = "/es/archive"
        [[languages.es.menu.main]]
          identifier = "About"
          name = "Acerca de"
          url = "/es/about"
        [[languages.es.menu.main]]
          identifier = "subscribe"
          name = "📩 Suscribirse"
          url = "/subscribe"
          weight = 1
        [[languages.es.menu.main]]
          identifier = "change_lang"
          name = "English"
          url = "/"
          weight = 3
        [[languages.es.menu.main]]
          identifier = "cv"
          name = "CV/Portfolio"
          url = "https://cv.franciscoyira.com/#projects"
          weight = 2

